apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: catalog-service
  name: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      move2kube.konveyor.io/service: catalog-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: catalog-service
      name: catalog-service
    spec:
      containers:
        - image: index.docker.io/korificf/catalog-service:latest
          imagePullPolicy: Always
          name: catalog-service
          ports:
            - containerPort: 8080
          resources: {}
      imagePullSecrets:
        - name: index-docker-io-imagepullsecret
      restartPolicy: Always
      securityContext: {}
status: {}
